spring:
  data:
    mongodb:
      username: angadgosain
      password: angadgosain
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
