spring:
  data:
    mongodb:
      username: angadgosain
      password: angadgosain
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.angadgosain.ecommerce.kafka.OrderConfirmation, paymentConfirmation:com.angadgosain.ecommerce.notification.PaymentNotificationRequest

  mail:
    host: localhost
    port: 1025
    username: angadgosain
    password: angadgosain
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        startls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  server:
    port: 8040
